http:
  port: 4910

admin:
  port: 9876
  host: localhost

apiEndpoints:
  cakes:
    host: localhost
    paths: '/cakes/?*'
  cart:
    host: localhost
    paths: '/cart/?*'
serviceEndpoints:
  cakesMS:
    url: 'http://localhost:6511'
  cartMS:
    url: 'http://localhost:6521'

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit

pipelines:
  cakes:
    apiEndpoints:
      - cakes
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: cakesMS
              changeOrigin: true
    
  cart:
    apiEndpoints:
      - cart
    policies:
      - proxy:
          - action:
              serviceEndpoint: cartMS
              changeOrigin: true
